global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "nodeanytime"
    static_configs:
      - targets: ["nodeserver:3001"]  # inside Docker network
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['localhost:9100']